### ISSUE TITLE
dotnet error

### ISSUE THREAD

**Issue by fammifarendra** [Ethic41/FingerPrint#1]
Enrollment Failed!
Fatal error: Uncaught com_exception: Failed to instantiate .Net object [CreateInstance] [0x80070002] The system cannot find the file specified. in D:\laragon\www\finger\src\core\enrollment.php:30 Stack trace: #0 D:\laragon\www\finger\src\core\enrollment.php(30): dotnet->dotnet('MyFPLib, Versio...', 'MyFPLib.FPLib') #1 D:\laragon\www\finger\src\core\enroll.php(27): fingerprint\Enrollment->createEnrollment() #2 {main} thrown in D:\laragon\www\finger\src\core\enrollment.php on line 30

**Comment by fammifarendra** [comment]
Problem solve, 
register MyFPLib.dll and MyBase64.dll to windows assembly with gacutil
Then the important thing is created htaccess that allow dll files

`<Files ~ "\.dll$">  
Allow From All
</Files>`

**Comment by godwindaniel101** [comment]
Hello thanks for your suggestion.. however when i created the htaccess file with your recommendation above, i am unable to access any file on the folder
